/**
 * insight.js — AnomalyIQ Plain-English Insight Report
 *
 * LLM summary paragraph, source badge, key stats row,
 * class distribution doughnut, reliability badge, caveat box.
 */

import { getInsightReport, getColumnConfig, getMetrics } from "./api.js";
import { getSession } from "./session.js";
import { showToast } from "./app.js";
import { renderClassDoughnut } from "./charts.js";

let _initialized = false;

// ── Init ──────────────────────────────────────────────────────────────────────

export async function init() {
  if (_initialized) return;
  _initialized = true;

  await _load();
}

export async function refresh() {
  _initialized = false;
  await init();
}

// ── Load ──────────────────────────────────────────────────────────────────────

async function _load() {
  const sessionId = getSession();
  if (!sessionId) return;

  _showSkeleton();

  try {
    const [report, cfg, metrics] = await Promise.all([
      getInsightReport(sessionId),
      getColumnConfig(sessionId),
      getMetrics(sessionId),
    ]);

    _renderReport(report, cfg, metrics);
  } catch (err) {
    showToast("Insight error", err.message, "error");
    _showError(err.message);
  }
}

// ── Render ────────────────────────────────────────────────────────────────────

function _renderReport(report, cfg, metrics) {
  // Main narrative
  const narrativeEl = document.getElementById("insight-narrative");
  if (narrativeEl) {
    narrativeEl.textContent = report.narrative || "No insight available.";
  }

  // Source badge
  const sourceEl = document.getElementById("insight-source-badge");
  if (sourceEl) {
    const isOpenRouter = report.source === "openrouter";
    sourceEl.textContent = isOpenRouter ? "Generated by OpenRouter" : "Local fallback narrative";
    sourceEl.className = `source-badge ${isOpenRouter ? "badge-accent" : "badge-muted"}`;
  }

  // Key stats row
  _renderKeyStats(report, metrics);

  // Class distribution doughnut
  const dist = cfg?.class_distribution || {};
  renderClassDoughnut("insight-doughnut", dist.class_0 || 0, dist.class_1 || 0);

  // Reliability badge
  _renderReliabilityBadge(report, cfg, metrics);

  // Caveat box for small datasets
  const nSamples = report.n_samples || cfg?.n_total || 0;
  const caveatEl = document.getElementById("insight-caveat");
  if (caveatEl) {
    if (nSamples < 1000) {
      caveatEl.classList.remove("hidden");
      caveatEl.innerHTML = `
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126z"/>
        </svg>
        <span>
          <strong>Small dataset warning:</strong>
          This model was trained on only <strong>${nSamples}</strong> samples
          (recommended: ≥1,000). Performance metrics may not generalize reliably.
          Consider gathering more data for production use.
        </span>
      `;
    } else {
      caveatEl.classList.add("hidden");
    }
  }
}

function _renderKeyStats(report, metrics) {
  const container = document.getElementById("insight-key-stats");
  if (!container) return;

  // Best model name
  const bestModelName = (report.best_model || "—").replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
  const bestAuc = report.best_auc ? (report.best_auc * 100).toFixed(1) + "%" : "—";

  // Top feature
  const topFeature = report.top_feature_human || report.top_feature || "—";
  const topFeatureScore = report.top_feature_score != null
    ? report.top_feature_score.toFixed(3)
    : "—";

  // SMOTE
  const smoteApplied = report.smote_applied || false;

  container.innerHTML = `
    <div class="stat-card accent-accent" style="text-align:center">
      <div class="stat-label">Best Model</div>
      <div class="stat-value" style="font-size:16px;line-height:1.3">${bestModelName}</div>
      <div class="stat-sub">AUC: <span class="mono" style="color:var(--accent)">${bestAuc}</span></div>
    </div>
    <div class="stat-card accent-ok" style="text-align:center">
      <div class="stat-label">Top Feature</div>
      <div class="stat-value" style="font-size:14px;font-family:'JetBrains Mono',monospace;line-height:1.3">${topFeature}</div>
      <div class="stat-sub">Score: <span class="mono" style="color:var(--ok)">${topFeatureScore}</span></div>
    </div>
    <div class="stat-card ${smoteApplied ? "accent-anomaly" : "accent-normal"}" style="text-align:center">
      <div class="stat-label">Class Balancing</div>
      <div class="stat-value" style="font-size:18px">${smoteApplied ? "SMOTE" : "Native"}</div>
      <div class="stat-sub">${smoteApplied ? "Applied to training data" : "No resampling needed"}</div>
    </div>
    <div class="stat-card" style="text-align:center">
      <div class="stat-label">Dataset Size</div>
      <div class="stat-value" style="font-size:24px">${report.n_samples?.toLocaleString() || "—"}</div>
      <div class="stat-sub">total samples</div>
    </div>
  `;
}

function _renderReliabilityBadge(report, cfg, metrics) {
  const el = document.getElementById("insight-reliability");
  if (!el) return;

  const bestAuc = report.best_auc || 0;
  const nSamples = report.n_samples || 0;

  let reliability, color, text;

  if (bestAuc >= 0.90 && nSamples >= 500) {
    reliability = "HIGH";
    color = "badge-ok";
    text = "High reliability — model generalizes well";
  } else if (bestAuc >= 0.75) {
    reliability = "MEDIUM";
    color = "badge-warn";
    text = "Medium reliability — adequate for most use cases";
  } else {
    reliability = "LOW";
    color = "badge-high";
    text = "Low reliability — collect more data or review features";
  }

  el.innerHTML = `
    <span class="badge ${color}">${reliability} RELIABILITY</span>
    <span style="font-size:12px;color:var(--txt3);margin-left:8px">${text}</span>
  `;
}

function _showSkeleton() {
  const narrativeEl = document.getElementById("insight-narrative");
  if (narrativeEl) {
    narrativeEl.innerHTML = `
      <div class="skeleton skeleton-text wide" style="height:16px;margin-bottom:8px"></div>
      <div class="skeleton skeleton-text wide" style="height:16px;margin-bottom:8px"></div>
      <div class="skeleton skeleton-text med" style="height:16px;margin-bottom:8px"></div>
    `;
  }
}

function _showError(msg) {
  const narrativeEl = document.getElementById("insight-narrative");
  if (narrativeEl) {
    narrativeEl.textContent = `Unable to load insight report: ${msg}`;
    narrativeEl.style.color = "var(--txt3)";
  }
}
